### ISSUE TITLE
Static/CSS Files

### ISSUE THREAD

**Issue by greatdiamondmoon** [dc-wdi-22/seekr-frontend#9]
How do I link my static CSS files to everything else in my project? I'm afraid I'm conflating express with react in regards to the static/css folder.

**Comment by aspittel** [comment]
I would follow the pattern that `create-react-app` sets for you where you import each CSS file into the component. So `App.css` would be for `App.js` and you import in that style.

**Comment by aspittel** [comment]
You could structure it differently, but that would be a good group discussion to have!

**Comment by greatdiamondmoon** [comment]
Thanks! So, we wouldn't create a style.css file within public?

**Comment by superbuggy** [comment]
With `create-react-app`, you can `import ./ComponentName.css` directly inside your `ComponentName.js`.

**Comment by superbuggy** [comment]
closing for now!
